# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Minecraft version
minecraft_version=26.1.2

# NeoForge versions
neoforge_full_version=26.1.2.22-beta
neoforge_loader_version=11
neo_version_range=[26.1.2,)

# Mod settings
mod_version=1.5.6
maven_group=com.breakinblocks
archives_base_name=auroral
mod_id=auroral
mod_name=Auroral
mod_author=Saereth

# Dependencies
guideme_version=26.1.10-alpha
